# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.3
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
    -   id: toml-sort-fix
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=80, fast_channels]
        pass_filenames: false
ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
