version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Use `git log` to check if the latest commit contains "bump: version",
      # if not, exit the command with 183 to cancel the build
      - '(git --no-pager log --pretty="tformat:%s -- %b" -1 | tr "\n" " " | grep -q "bump: version") || exit 183'
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv sync --group docs
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
sphinx:
   configuration: docs/conf.py
