src = ["fast-channels", "tests"]
target-version = "py311"

[lint]
select = ["B", "C90", "E", "F", "I", "N", "N", "PL", "Q", "UP", "W"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
